### ISSUE TITLE
Adding stroke and weight option to addGlPolygons

### ISSUE THREAD

**Issue by BastienFR** [r-spatial/leafgl#17] opened 2019-04-08 18:20 UTC
Hello,

I need to make a map with `leafgl` where the polygons have a color inside and a thin border.  I'm able to do it with `leaflet` but not `leafgl`.  Is there an option that I missed or could it be implemented?

RE:
# data preparation:
```
library(sf)  
library(leaflet)
library(leafgl)
library(colourvalues)

nc <- st_read(system.file("gpkg/nc.gpkg", package="sf"), quiet = TRUE) %>% 
  st_transform(st_crs(4326)) %>% 
  st_cast('POLYGON')

cols = colour_values_rgb(nc$AREA, palette = "inferno", include_alpha = FALSE) / 255
colpal <- colorNumeric(palette = "inferno", domain=nc$AREA, n=10)
```

# using `leaflet`:
```
leaflet(data=nc) %>% 
  addProviderTiles(provider = providers$OpenStreetMap) %>%
  addPolygons(color  = ~colpal(AREA),
              stroke = T,
              weight = 0.8) 
```

gives:

![mori](https://user-images.githubusercontent.com/10979480/55746826-c3a32d00-5a08-11e9-8ff1-af6f1d1a8f60.PNG)

Which has nice borders.

# with `leafgl`
```
leaflet() %>%
   addProviderTiles(provider = providers$OpenStreetMap) %>%
   addGlPolygons(nc, color = cols,stroke = T,
                 weight = 0.8) %>% 
   fitBounds(lng1 = unname(st_bbox(nc)$xmin), lng2 = unname(st_bbox(nc)$xmax), lat1 = unname(st_bbox(nc)$ymin), lat2 = unname(st_bbox(nc)$ymax))
Error in geojsonsf::sf_geojson(data, ...) : 
  unused arguments (stroke = T, weight = 0.8)
```

gives an error and if I remove the bad arguments (`stroke = T` and `weight = 0.8`), I get:
![mgl](https://user-images.githubusercontent.com/10979480/55746949-14b32100-5a09-11e9-9de8-c2e2185801de.PNG)

Which has no borders.  Is there an equivalent of the  `stroke = T` and `weight = 0.8` arguments in leafgl?

Thanks

**Comment by tim-salabim** [comment] 2019-04-09 05:47
I'm gonna close this here, as it is a duplicate of #3 which also contains a link to the original issue in the underlying js lib. Also, I don't think that linewidth will be controllable in leafgl, see discussion here https://github.com/r-spatial/leafgl/issues/3

**Closed by tim-salabim** 2019-04-09 05:47 UTC
